insert into cibucks.userProfiles (PK,key,profile) values(1,1,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')

-- drop index cibucks.interestIds id_groupId
CREATE MAPKEYS INDEX mpk_id_groupId ON cibucks.campaigns (profile) string
CREATE MAPVALUES INDEX mpv_id_groupId on cibucks.campaigns (profile) numeric
CREATE LIST INDEX id_groupId on cibucks.campaigns (profile) numeric


insert into cibucks.campaigns (PK,key,profile) values(1,1,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(2,2,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(3,3,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(4,4,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(5,5,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(6,6,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(7,7,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(8,8,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(9,9,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(10,10,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(11,11,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(12,12,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(13,13,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(14,14,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(15,15,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(16,16,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(17,17,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(18,18,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(19,19,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(20,20,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(21,21,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(22,22,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(23,23,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(24,24,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(25,25,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(26,26,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(27,27,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(28,28,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(29,29,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(30,30,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(31,31,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(32,32,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(33,33,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(34,34,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(35,35,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(36,36,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(37,37,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(38,38,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(39,39,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(40,40,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(41,41,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(42,42,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(43,43,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(44,44,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(45,45,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(46,46,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(47,47,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(48,48,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(49,49,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(50,50,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(51,51,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(52,52,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(53,53,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(54,54,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(55,55,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(56,56,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(57,57,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(58,58,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(59,59,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(60,60,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(61,61,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(62,62,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(63,63,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(64,64,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(65,65,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(66,66,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(67,67,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(68,68,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(69,69,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(70,70,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(71,71,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(72,72,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(73,73,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(74,74,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(75,75,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(76,76,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(77,77,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(78,78,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(79,79,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(80,80,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(81,81,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(82,82,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(83,83,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(84,84,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(85,85,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(86,86,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(87,87,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(88,88,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(89,89,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(90,90,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(91,91,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(92,92,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(93,93,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(94,94,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(95,95,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(96,96,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(97,97,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(98,98,'JSON[{"interestIds":[11, 21], "groupId":22}, {"interestIds":[3, 45, 32], "groupId":3}]')
insert into cibucks.campaigns (PK,key,profile) values(99,99,'JSON[{"interestIds":[23], "groupId":1}, {"interestIds":[3], "groupId":2}]')
insert into cibucks.campaigns (PK,key,profile) values(100,100,'JSON[{"interestIds":[1, 2], "groupId":1}, {"interestIds":[4, 5], "groupId":2}]')
